label{
    monitor =
    text = $TIME
    font_size = 60
    font_family = JetBrains Bold
    position = 0, 0
    halign = center
    valign = center
    shadow_passes = 2
    shadow_size = 1
}

background {
    monitor =
    path = /home/linus_kid/Pictures/wallpapers/1.png
    blur_passes = 3
    blur_size = 1 
}

input_field{
    size = 250, 60
    outline_thickness = 1

}

